"""initial relational schema

Revision ID: 0001
Revises: 
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_challenges',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('purpose', sa.String(length=8), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('consumed_at', sa.Integer(), nullable=True),
    sa.CheckConstraint("length(username) BETWEEN 3 AND 32 AND username NOT GLOB '*[^a-z0-9_]*'", name='ck_challenges_username'),
    sa.CheckConstraint("purpose IN ('register','login')", name='ck_challenges_purpose'),
    sa.CheckConstraint('attempts BETWEEN 0 AND 5', name='ck_challenges_attempts'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_challenges', schema=None) as batch_op:
        batch_op.create_index('ix_challenges_expires', ['expires_at'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('avatar_key', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.CheckConstraint("avatar_key IN ('sky','fern','sun','clay')", name='ck_users_avatar'),
    sa.CheckConstraint("length(username) BETWEEN 3 AND 32 AND username NOT GLOB '*[^a-z0-9_]*'", name='ck_users_username'),
    sa.CheckConstraint('length(trim(display_name)) BETWEEN 1 AND 80', name='ck_users_display_name'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('contacts',
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('contact_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.CheckConstraint('owner_id != contact_user_id', name='ck_contacts_nonself'),
    sa.ForeignKeyConstraint(['contact_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('owner_id', 'contact_user_id')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index('ix_contacts_reverse', ['contact_user_id'], unique=False)

    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=6), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('direct_low_user_id', sa.Integer(), nullable=True),
    sa.Column('direct_high_user_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('last_activity_at', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.CheckConstraint("(kind = 'direct' AND name IS NULL AND direct_low_user_id IS NOT NULL AND direct_high_user_id IS NOT NULL AND direct_low_user_id < direct_high_user_id) OR (kind = 'group' AND direct_low_user_id IS NULL AND direct_high_user_id IS NULL AND name IS NOT NULL AND length(trim(name)) BETWEEN 1 AND 100)", name='ck_conversations_kind_pair'),
    sa.CheckConstraint('version >= 1', name='ck_conversations_version'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['direct_high_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['direct_low_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('direct_low_user_id', 'direct_high_user_id', name='uq_conversations_direct_pair')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index('ix_conversations_activity', [sa.literal_column('last_activity_at DESC'), sa.literal_column('id DESC')], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.Column('revoked_at', sa.Integer(), nullable=True),
    sa.CheckConstraint('expires_at > created_at', name='ck_sessions_expiry'),
    sa.CheckConstraint('length(token_hash) = 64', name='ck_sessions_hash'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index('ix_sessions_expires', ['expires_at'], unique=False)
        batch_op.create_index('ix_sessions_user_revoked', ['user_id', 'revoked_at'], unique=False)

    op.create_table('conversation_members',
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=6), nullable=False),
    sa.Column('joined_at', sa.Integer(), nullable=False),
    sa.Column('removed_at', sa.Integer(), nullable=True),
    sa.CheckConstraint("role IN ('admin','member')", name='ck_members_role'),
    sa.CheckConstraint('removed_at IS NULL OR removed_at >= joined_at', name='ck_members_removed'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('conversation_id', 'user_id')
    )
    with op.batch_alter_table('conversation_members', schema=None) as batch_op:
        batch_op.create_index('ix_members_conversation_role', ['conversation_id', 'removed_at', 'role'], unique=False)
        batch_op.create_index('ix_members_user_active', ['user_id', 'removed_at', 'conversation_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('client_message_id', sa.String(length=36), nullable=False),
    sa.Column('body', sa.String(length=4000), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.CheckConstraint("length(client_message_id) = 36 AND substr(client_message_id,9,1) = '-' AND substr(client_message_id,14,1) = '-' AND substr(client_message_id,19,1) = '-' AND substr(client_message_id,24,1) = '-' AND length(replace(client_message_id,'-','')) = 32 AND replace(client_message_id,'-','') NOT GLOB '*[^0-9a-f]*'", name='ck_messages_uuid'),
    sa.CheckConstraint('length(trim(body)) BETWEEN 1 AND 4000', name='ck_messages_body'),
    sa.ForeignKeyConstraint(['conversation_id', 'sender_id'], ['conversation_members.conversation_id', 'conversation_members.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'id', name='uq_messages_conversation_id'),
    sa.UniqueConstraint('sender_id', 'client_message_id', name='uq_messages_sender_client'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('ix_messages_history', ['conversation_id', sa.literal_column('id DESC')], unique=False)

    op.create_table('message_receipts',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('delivered_at', sa.Integer(), nullable=True),
    sa.Column('read_at', sa.Integer(), nullable=True),
    sa.CheckConstraint('read_at IS NULL OR (delivered_at IS NOT NULL AND read_at >= delivered_at)', name='ck_receipts_read_delivery'),
    sa.ForeignKeyConstraint(['conversation_id', 'message_id'], ['messages.conversation_id', 'messages.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['conversation_id', 'recipient_id'], ['conversation_members.conversation_id', 'conversation_members.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('message_id', 'recipient_id')
    )
    with op.batch_alter_table('message_receipts', schema=None) as batch_op:
        batch_op.create_index('ix_receipts_unread', ['recipient_id', 'conversation_id', 'message_id'], unique=False, sqlite_where=sa.text('read_at IS NULL'))

    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_receipts', schema=None) as batch_op:
        batch_op.drop_index('ix_receipts_unread', sqlite_where=sa.text('read_at IS NULL'))

    op.drop_table('message_receipts')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('ix_messages_history')

    op.drop_table('messages')
    with op.batch_alter_table('conversation_members', schema=None) as batch_op:
        batch_op.drop_index('ix_members_user_active')
        batch_op.drop_index('ix_members_conversation_role')

    op.drop_table('conversation_members')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_sessions_user_revoked')
        batch_op.drop_index('ix_sessions_expires')

    op.drop_table('sessions')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index('ix_conversations_activity')

    op.drop_table('conversations')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index('ix_contacts_reverse')

    op.drop_table('contacts')
    op.drop_table('users')
    with op.batch_alter_table('auth_challenges', schema=None) as batch_op:
        batch_op.drop_index('ix_challenges_expires')

    op.drop_table('auth_challenges')
    # ### end Alembic commands ###
